export const SAMPLE_PRODUCTS = {
  products: [
    {
      id: "1",
      name: "Premium Wireless Headphones",
      price: 599,
      currency: "GHS",
      images: [
        "https://picsum.photos/seed/headphones/500/500",
      ],
      category: "Electronics",
      is_featured: true,
      is_promoted: true,
      promotion_tag: "Sale",
      description:
        "High-quality wireless headphones with noise cancellation and 30-hour battery life",
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      name: "Luxury Leather Wallet",
      price: 299,
      currency: "GHS",
      images: [
        "https://picsum.photos/seed/wallet/500/500",
      ],
      category: "Accessories",
      is_featured: true,
      is_promoted: false,
      description: "Premium leather wallet with RFID protection",
      created_at: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: "3",
      name: "Stainless Steel Water Bottle",
      price: 149,
      currency: "GHS",
      images: [
        "https://picsum.photos/seed/bottle/500/500",
      ],
      category: "Lifestyle",
      is_featured: false,
      is_promoted: true,
      promotion_tag: "New",
      description: "Keeps drinks hot for 24 hours or cold for 36 hours",
      created_at: new Date(Date.now() - 172800000).toISOString(),
    },
    {
      id: "4",
      name: "Smart Watch Ultra",
      price: 899,
      currency: "GHS",
      images: [
        "https://picsum.photos/seed/watch/500/500",
      ],
      category: "Electronics",
      is_featured: true,
      is_promoted: false,
      description: "Advanced fitness tracking with 14-day battery life",
      created_at: new Date(Date.now() - 259200000).toISOString(),
    },
    {
      id: "5",
      name: "Premium Coffee Maker",
      price: 449,
      currency: "GHS",
      images: [
        "https://picsum.photos/seed/coffee/500/500",
      ],
      category: "Home & Kitchen",
      is_featured: false,
      is_promoted: false,
      description: "Brew perfect coffee with programmable brewing options",
      created_at: new Date(Date.now() - 345600000).toISOString(),
    },
    {
      id: "6",
      name: "Compact Camera",
      price: 1299,
      currency: "GHS",
      images: [
        "https://picsum.photos/seed/camera/500/500",
      ],
      category: "Electronics",
      is_featured: true,
      is_promoted: true,
      promotion_tag: "Flash Sale",
      description: "Professional-grade compact camera for photography enthusiasts",
      created_at: new Date(Date.now() - 432000000).toISOString(),
    },
    {
      id: "7",
      name: "Yoga Mat Premium",
      price: 199,
      currency: "GHS",
      images: [
        "https://picsum.photos/seed/yoga/500/500",
      ],
      category: "Fitness",
      is_featured: false,
      is_promoted: false,
      description: "Non-slip eco-friendly yoga mat with carrying strap",
      created_at: new Date(Date.now() - 518400000).toISOString(),
    },
    {
      id: "8",
      name: "Portable Speaker",
      price: 349,
      currency: "GHS",
      images: [
        "https://picsum.photos/seed/speaker/500/500",
      ],
      category: "Electronics",
      is_featured: false,
      is_promoted: true,
      promotion_tag: "Trending",
      description: "Waterproof Bluetooth speaker with 360-degree sound",
      created_at: new Date(Date.now() - 604800000).toISOString(),
    },
  ],
  categories: ["Electronics", "Accessories", "Lifestyle", "Home & Kitchen", "Fitness"],
};
