export const SAMPLE_PRODUCTS = {
  products: [
    {
      id: "1",
      name: "Premium Wireless Headphones",
      price: 599,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop",
      ],
      category: "Electronics",
      is_featured: true,
      is_promoted: true,
      promotion_tag: "Sale",
      description:
        "High-quality wireless headphones with noise cancellation and 30-hour battery life",
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      name: "Luxury Leather Wallet",
      price: 299,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&h=500&fit=crop",
      ],
      category: "Accessories",
      is_featured: true,
      is_promoted: false,
      description: "Premium leather wallet with RFID protection",
      created_at: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: "3",
      name: "Stainless Steel Water Bottle",
      price: 149,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1602827860917-0ad8e95d92d2?w=500&h=500&fit=crop",
      ],
      category: "Lifestyle",
      is_featured: false,
      is_promoted: true,
      promotion_tag: "New",
      description: "Keeps drinks hot for 24 hours or cold for 36 hours",
      created_at: new Date(Date.now() - 172800000).toISOString(),
    },
    {
      id: "4",
      name: "Smart Watch Ultra",
      price: 899,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop",
      ],
      category: "Electronics",
      is_featured: true,
      is_promoted: false,
      description: "Advanced fitness tracking with 14-day battery life",
      created_at: new Date(Date.now() - 259200000).toISOString(),
    },
    {
      id: "5",
      name: "Premium Coffee Maker",
      price: 449,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1517668808822-9ebb02ae2a0e?w=500&h=500&fit=crop",
      ],
      category: "Home & Kitchen",
      is_featured: false,
      is_promoted: false,
      description: "Brew perfect coffee with programmable brewing options",
      created_at: new Date(Date.now() - 345600000).toISOString(),
    },
    {
      id: "6",
      name: "Compact Camera",
      price: 1299,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=500&h=500&fit=crop",
      ],
      category: "Electronics",
      is_featured: true,
      is_promoted: true,
      promotion_tag: "Flash Sale",
      description: "Professional-grade compact camera for photography enthusiasts",
      created_at: new Date(Date.now() - 432000000).toISOString(),
    },
    {
      id: "7",
      name: "Yoga Mat Premium",
      price: 199,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&h=500&fit=crop",
      ],
      category: "Fitness",
      is_featured: false,
      is_promoted: false,
      description: "Non-slip eco-friendly yoga mat with carrying strap",
      created_at: new Date(Date.now() - 518400000).toISOString(),
    },
    {
      id: "8",
      name: "Portable Speaker",
      price: 349,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1589003077984-894e133814c9?w=500&h=500&fit=crop",
      ],
      category: "Electronics",
      is_featured: false,
      is_promoted: true,
      promotion_tag: "Trending",
      description: "Waterproof Bluetooth speaker with 360-degree sound",
      created_at: new Date(Date.now() - 604800000).toISOString(),
    },
  ],
  categories: ["Electronics", "Accessories", "Lifestyle", "Home & Kitchen", "Fitness"],
};
